### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by FarhanAliRaza** [dsweb19778/AppleIDChecker#1]

**Comment by FarhanAliRaza** [comment]
response returned for my request
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta http-equiv="Content-Script-Type" content="text/javascript">
        <meta name="description" content="Store contacts, calendars, photos, music, books, apps and more in the cloud and access them on all your devices.">
        <meta name="keywords" content="icloud, free, apple">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="default">
        <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link rel="stylesheet" href="/IDMSWebAuth/static/13Jan2021/views/static/css/App1876/login_style.css" type="text/css" media="screen, projection">
        <title>Login</title>
    </head>
    <body>
        <div id="wrap">
            <div id="content">
             
                <div id="login_box" class="login_shadow">





<meta name="robots" content="noindex">

<link rel="stylesheet" type="text/css" href="/IDMSWebAuth/static/13Jan2021/views/static/css/common/commonLogin.css" charset="utf-8"/>
<script type="text/javaScript" src="/IDMSWebAuth/static/13Jan2021/views/static/common.js"></script>
<script type="text/javaScript" src="/IDMSWebAuth/static/13Jan2021/views/static/Appjavascripts/FDC/dcutil_2_2.js"></script>
<script src="/IDMSWebAuth/static/13Jan2021/views/static/js/commonLogin.js" type="text/javascript" charset="utf-8"></script>
<script src="/IDMSWebAuth/static/13Jan2021/views/static/js/commonScript.js" type="text/javascript" charset="utf-8"></script>








<input type="hidden" id="harvestID" value="none" />
<input type="hidden" id="expiryID" value="none" />


                <input type="hidden" id="authenticationID" value="true" />




        <input type="hidden" value="modern" id="modernview"></input>
        <table width="100%">
                <tbody>
                <tr>

                                <td width="30%"></td>

                        <td>

                                <div id="ds_container"><form id="command" name="form1" novalidate="true" action="/authenticate" method="post">

                                        <input id="iForgotNewWindowVar" name="openiForgotInNewWindow" type="hidden" value="false" value="false"/>
                                        <input id="fdcBrowserData" name="fdcBrowserData" type="hidden" value=""/>

                                        


                                        <div class="formrow" id="formRowDiv">


                                                        <span class="formwrap"
                                                                  id="formwrapstyle"> <input id="accountname" name="appleId" tabindex="1" autocorrect="off" spellcheck="false" data-value="form1" name="theAccountName" type="text" class="input-text" autocapitalize="off" aria-label="Apple ID" value="farhanalirazaazeemi@icloud.com" size="30" maxlength="128" autocomplete="off"/> </span>





                                                                        <span class="alert"></span>


                                                        <div class="space padder1">



                                                        <span class="input-msg red show">



                                                                        Your Apple ID or password was entered incorrectly.

                                                        </span>


                                                        </div>

                                                <div class="space padder2"> <span class="input-msg show"> 


                                                        <a id="appleIdURL" data-eval="true" data-value="https%3A%2F%2Fidmsa.apple.com%2FIDMSWebAuth%2Flogin.html%3Flanguage%3DUS-EN%26rv%3D0%26appIdKey%3Dc991a1687d72e54d35d951a58cf7aa33fe722353b48f89d27c1ea2ffa08a4b80"
                                                           href="https://appleconnect.apple.com/iforgot?language=US-EN&app_id=1289&s=548-548">Forgot your Apple ID?</a>

                                         </span></div></div>
                                        <div class="formrow">






                                                <span class="formwrap"
                                                          id="formwrapstyle1"> <input id="accountpassword" name="accountPassword" tabindex="2" autocorrect="off" data-value="form1" autocapitalize="off" aria-label="Password" type="password" value="" size="30" autocomplete="off"/> 
                                        </span><div class="space padder3"><span
                                                        class="input-msg show"> 


                                                        <a id="passwordURL" data-value="https%3A%2F%2Fidmsa.apple.com%2FIDMSWebAuth%2Flogin.html%3Flanguage%3DUS-EN%26rv%3D0%26appIdKey%3Dc991a1687d72e54d35d951a58cf7aa33fe722353b48f89d27c1ea2ffa08a4b80"
                                                           href="https://appleconnect.apple.com/iforgot?language=US-EN&app_id=1289&s=548-548"
                                                           >Forgot your password?</a>

                                         </span></div></div>

                                        <div id="bot-nav">  
                                                <a class="btn bigblue" id="commonLoginSigninAnchor"><input type="submit"
                                                                                        id="signInHyperLink" tabindex="3"
                                                                                        value='Sign In'
                                                                                        aria-label='Sign In'
                                                                                        title='Sign In' /></a>
                                        </div>





        <input type="hidden" id="appIdKey" name="appIdKey"
                value="c991a1687d72e54d35d951a58cf7aa33fe722353b48f89d27c1ea2ffa08a4b80" />




        <input type="hidden" id="accNameLocked" name="accNameLocked"
                value="false" />



<input type="hidden" id="language" name="language"
        value="US-EN" />






        <input type="hidden" id="requestUri" name="requestUri" value="/authenticate"/>




        <input type="hidden" id="Env" name="Env" value="PROD" />



















        <input type="hidden" id="referer" name="referer"
                value="https://idmsa.apple.com/login.html?appIdKey=c991a1687d72e54d35d951a58cf7aa33fe722353b48f89d27c1ea2ffa08a4b80" />

<input type="hidden" id="scnt" name="scnt" value="AAAAKjRFRkM2MkIxNTc3QTRFQkFGRERERDYzQjY3RThDNEUxfDEAAAF6te200cUkQmB2OhljoWbOmBpsWDcMPvMdaXSRgVHRXPq9YOFaj6BL+q0WNJcAJhE1aKZpqyNLLR+/DAeWApCHmxwO0cg0AurEn5/CA9e6/6QUo2Ip" />


                                </form></div>
                        </td>
                        <td class="cellspacer" width="30%"></td>
                </tr>
                </tbody>
        </table>
        <input id="appleIdHide" type="hidden"
                   value='Apple ID' />

        <input type="hidden" id="accountPasswordHide"
                   value='Password' />






<script type="application/json" id="common_login_boot_args">
{
        "requestFromDevice": "false",
        "accountNameReadOnly": "false"
}
</script>
<script type="text/javascript" src="/IDMSWebAuth/static/13Jan2021/views/static/js/boot/common/commonLogin_boot.js"></script>













    
    

<input type="hidden" name="hiddenUrl" id="hiddenUrl">
<input type="hidden" name="currentUrl" id="currentUrl">
<input id="emptyCredentialsErrMessage" type="hidden" value='Please enter your Apple ID and password.'/>










   
<script type="text/javascript" src="/IDMSWebAuth/static/13Jan2021/views/static/Appjavascripts/App1876/login_boot.js"></script>
<div id="signin"> <input  id="passwordbtn" class="butn" type="button" value="Sign In"></div>  
   
   </div>
               
                <div id="gradient_radial">
                    
                
                                        <div id="footer">
                                                <p class="footer_forgot" id="forgotapplepassword"> Did you forget your password?
<a href="https://iforgot.apple.com/">Click Here</a></p>
                                                <p class="footer_copyright"> Copyright &copy 2021 Apple Inc. All rights reserved.<a href="http://www.apple.com/legal/" target="_blank">Terms Of Use</a>
                                                                &nbsp;|&nbsp;
                                                                <a href="http://www.apple.com/legal/privacy/" target="_blank">Privacy Policy</a></p>
                                        </div>
                  
                </div>
            </div>
        </div>     
         <script type="text/javascript" src="/IDMSWebAuth/static/13Jan2021/views/static/Appjavascripts/App1876/appFooter_boot.js"></script>
    </body>
</html>
(project_env) root@app:/home/veri_fro/appl/inc# python api.py


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta http-equiv="Content-Script-Type" content="text/javascript">
        <meta name="description" content="Store contacts, calendars, photos, music, books, apps and more in the cloud and access them on all your devices.">
        <meta name="keywords" content="icloud, free, apple">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="default">
        <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link rel="stylesheet" href="/IDMSWebAuth/static/13Jan2021/views/static/css/App1876/login_style.css" type="text/css" media="screen, projection">
        <title>Login</title>
    </head>
    <body>
        <div id="wrap">
            <div id="content">
             
                <div id="login_box" class="login_shadow">





<meta name="robots" content="noindex">

<link rel="stylesheet" type="text/css" href="/IDMSWebAuth/static/13Jan2021/views/static/css/common/commonLogin.css" charset="utf-8"/>
<script type="text/javaScript" src="/IDMSWebAuth/static/13Jan2021/views/static/common.js"></script>
<script type="text/javaScript" src="/IDMSWebAuth/static/13Jan2021/views/static/Appjavascripts/FDC/dcutil_2_2.js"></script>
<script src="/IDMSWebAuth/static/13Jan2021/views/static/js/commonLogin.js" type="text/javascript" charset="utf-8"></script>
<script src="/IDMSWebAuth/static/13Jan2021/views/static/js/commonScript.js" type="text/javascript" charset="utf-8"></script>








<input type="hidden" id="harvestID" value="none" />
<input type="hidden" id="expiryID" value="none" />


                <input type="hidden" id="authenticationID" value="true" />




        <input type="hidden" value="modern" id="modernview"></input>
        <table width="100%">
                <tbody>
                <tr>

                                <td width="30%"></td>

                        <td>

                                <div id="ds_container"><form id="command" name="form1" novalidate="true" action="/authenticate" method="post">

                                        <input id="iForgotNewWindowVar" name="openiForgotInNewWindow" type="hidden" value="false" value="false"/>
                                        <input id="fdcBrowserData" name="fdcBrowserData" type="hidden" value=""/>

                                        


                                        <div class="formrow" id="formRowDiv">


                                                        <span class="formwrap"
                                                                  id="formwrapstyle"> <input id="accountname" name="appleId" tabindex="1" autocorrect="off" spellcheck="false" data-value="form1" name="theAccountName" type="text" class="input-text" autocapitalize="off" aria-label="Apple ID" value="sdjkalsjasd@icloud.com" size="30" maxlength="128" autocomplete="off"/> </span>





                                                                        <span class="alert"></span>


                                                        <div class="space padder1">



                                                        <span class="input-msg red show">



                                                                        Your Apple ID or password was entered incorrectly.

                                                        </span>


                                                        </div>

                                                <div class="space padder2"> <span class="input-msg show"> 


                                                        <a id="appleIdURL" data-eval="true" data-value="https%3A%2F%2Fidmsa.apple.com%2FIDMSWebAuth%2Flogin.html%3Flanguage%3DUS-EN%26rv%3D0%26appIdKey%3Dc991a1687d72e54d35d951a58cf7aa33fe722353b48f89d27c1ea2ffa08a4b80"
                                                           href="https://appleconnect.apple.com/iforgot?language=US-EN&app_id=1289&s=548-548">Forgot your Apple ID?</a>

                                         </span></div></div>
                                        <div class="formrow">






                                                <span class="formwrap"
                                                          id="formwrapstyle1"> <input id="accountpassword" name="accountPassword" tabindex="2" autocorrect="off" data-value="form1" autocapitalize="off" aria-label="Password" type="password" value="" size="30" autocomplete="off"/> 
                                        </span><div class="space padder3"><span
                                                        class="input-msg show"> 


                                                        <a id="passwordURL" data-value="https%3A%2F%2Fidmsa.apple.com%2FIDMSWebAuth%2Flogin.html%3Flanguage%3DUS-EN%26rv%3D0%26appIdKey%3Dc991a1687d72e54d35d951a58cf7aa33fe722353b48f89d27c1ea2ffa08a4b80"
                                                           href="https://appleconnect.apple.com/iforgot?language=US-EN&app_id=1289&s=548-548"
                                                           >Forgot your password?</a>

                                         </span></div></div>

                                        <div id="bot-nav">  
                                                <a class="btn bigblue" id="commonLoginSigninAnchor"><input type="submit"
                                                                                                                                                                                                   id="signInHyperLink" tabindex="3"
                                                                                                                                                                                                   value='Sign In'
                                                                                                                                                                                                   aria-label='Sign In'
                                                                                                                                                                                                   title='Sign In' /></a>
                                        </div>





        <input type="hidden" id="appIdKey" name="appIdKey"
                value="c991a1687d72e54d35d951a58cf7aa33fe722353b48f89d27c1ea2ffa08a4b80" />




        <input type="hidden" id="accNameLocked" name="accNameLocked"
                value="false" />



<input type="hidden" id="language" name="language"
        value="US-EN" />






        <input type="hidden" id="requestUri" name="requestUri" value="/authenticate"/>




        <input type="hidden" id="Env" name="Env" value="PROD" />



















        <input type="hidden" id="referer" name="referer"
                value="https://idmsa.apple.com/login.html?appIdKey=c991a1687d72e54d35d951a58cf7aa33fe722353b48f89d27c1ea2ffa08a4b80" />

<input type="hidden" id="scnt" name="scnt" value="AAAAKkEwN0IxQTAxNjU0QjJGQ0EyNDNFNTk1OTc2OTRFNDBFfDEAAAF6tfoBx8i9DOPA0B2xMpNIPKCL8S+27sGyQv6pmXwl4NjICzPYOiDflZGmn3AAJhHxGfg518q8C4BcGu9oPY/NubnFIFk2iH4BPFI2wsVoQ3AnCaVC" />


                                </form></div>
                        </td>
                        <td class="cellspacer" width="30%"></td>
                </tr>
                </tbody>
        </table>
        <input id="appleIdHide" type="hidden"
                   value='Apple ID' />

        <input type="hidden" id="accountPasswordHide"
                   value='Password' />






<script type="application/json" id="common_login_boot_args">
{
        "requestFromDevice": "false",
        "accountNameReadOnly": "false"
}
</script>
<script type="text/javascript" src="/IDMSWebAuth/static/13Jan2021/views/static/js/boot/common/commonLogin_boot.js"></script>













    
    

<input type="hidden" name="hiddenUrl" id="hiddenUrl">
<input type="hidden" name="currentUrl" id="currentUrl">
<input id="emptyCredentialsErrMessage" type="hidden" value='Please enter your Apple ID and password.'/>










   
<script type="text/javascript" src="/IDMSWebAuth/static/13Jan2021/views/static/Appjavascripts/App1876/login_boot.js"></script>
<div id="signin"> <input  id="passwordbtn" class="butn" type="button" value="Sign In"></div>  
   
   </div>
               
                <div id="gradient_radial">
                    
                
                                        <div id="footer">
                                                <p class="footer_forgot" id="forgotapplepassword"> Did you forget your password?
<a href="https://iforgot.apple.com/">Click Here</a></p>
                                                <p class="footer_copyright"> Copyright &copy 2021 Apple Inc. All rights reserved.<a href="http://www.apple.com/legal/" target="_blank">Terms Of Use</a>
                                                                &nbsp;|&nbsp;
                                                                <a href="http://www.apple.com/legal/privacy/" target="_blank">Privacy Policy</a></p>
                                        </div>
                  
                </div>
            </div>
        </div>     
         <script type="text/javascript" src="/IDMSWebAuth/static/13Jan2021/views/static/Appjavascripts/App1876/appFooter_boot.js"></script>
    </body>
</html>

**Comment by dsweb19778** [comment]
The script working fine please check your python version
